config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :users do
    resources :admins
    resources :students do
      collection do
        post :import
      end
    end
    resources :teachers do
      collection do
        post :import
      end
    end
  end
  
  namespace :settings do
    resource :penalty_costs
    resource :backups
  end

  resources :borrowers do
    collection do 
      get :ajax_select2
    end
  end

  resources :books do
    collection do
      post :import
    end
  end
  
  resources :returns do
    collection do
      post :add_book
    end
  end
  
  resources :loans do 
    collection do
      post :add_book
    end
  end

  resources :write_offs do
    collection do
      post :add_book
    end
  end

  resources :late_returns

  namespace :reports do
    resources :loans do
      collection do
        get :top_rank
        get :by_year
        get :by_class
        get :detail
        post :detail
      end
    end
  end

  root "users/students#index"
end

app/models/write_off.rb
class WriteOff < ApplicationRecord
  monetize :total_price_cents, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :user  
  has_many :write_off_books

  accepts_nested_attributes_for :write_off_books, allow_destroy: true
end

app/controllers/write_offs_controller.rb
class WriteOffsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_write_off, only: %I[show]

  def index
    respond_to do |format|
      format.html
      format.json { render json: WriteOffsDatatable.new(view_context) }
    end
  end

  def new
    @write_off = WriteOff.new
    @write_off.write_off_date = Time.zone.today
  end

  def show; end

  def create
    @write_off = WriteOff.new(write_off_params)
    set_write_off_books
    if @write_off.save
      flash[:success] = "This write off has been created."
      redirect_to write_off_path(@write_off)
    else
      flash[:error] = "Sorry unable to create book due to #{@write_off.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def add_book
    @book = Book.find_by(barcode: params[:barcode])
  end

  private

  def write_off_params
    params.require(:write_off).permit([:write_off_date, :remark, write_off_books_attributes: [:id, :book_id]])
  end

  def set_write_off
    @write_off = WriteOff.find(params[:id])
  end

  def set_write_off_books
    @write_off.write_off_books.each do |write_off_book|
      write_off_book.user_id = current_user.id
      write_off_book.price = write_off_book&.book&.price
    end
    @write_off.user_id = current_user.id
    @write_off.total_quantity = @write_off.write_off_books.size
    @write_off.total_price = @write_off.write_off_books.collect{|x| x.price}.sum
  end
end

app/views/write_offs/add_book.js.erb
$(".barcode-input").val("")

<% if @book.present? %>
  if ($("#book-id-<%= @book.id %>").size() == 0) {
    $(".add-book-table").find("tbody").append("<%= j render partial: 'write_offs/partials/add_book', locals: { book: @book } %>")
  } else {
    alert("Book already added!")
  }
<% else %>
  alert("Book not found! Please scan again.")
<% end %>

app/views/write_offs/index.html.slim
.container
  .row
    .col-12
      .float-left
        h2 Write Offs
      .float-right
        = link_to "Add New Write Off", new_write_off_path, class: "btn btn-success"
  hr

  table.table.ajax-datatable data-source="#{write_offs_path(format: :json)}"
    thead
      tr
        th #
        th Name
        th Year
        th Price
        th Write Off Date

app/views/write_offs/new.html.slim
.container
  .row
    .col-12
      .float-left
        h2 New Write Off
  hr
  .row
    .col-12
      = form_for "", url: add_book_write_offs_path, remote: true, method: :post do |f|        
        .d-flex.justify-content-center
          .form-group.col-8.mb-5
            = f.label :barcode, "Scan Barcode Here", class: "text-center"
            = text_field "", "barcode", class: "form-control barcode-input", placeholder: "Scan Barcode Here"
    .col-12
      = form_for @write_off do |f|    
        .row   
          .col-4
            .form-group
              = f.label :write_off_date, "Loan Date"
              = f.text_field :write_off_date, class: "form-control", readonly: true, value: l(@write_off.write_off_date.to_date, format: :default)

            .form-group
              = f.label :remark, "Remark"
              = f.text_area :remark, class: "form-control", placeholder: "Remark"
          
          .col-8          
            .col-12.mb-5
              table.table.table-sm.add-book-table
                thead
                  tr
                    th.col-10 Books
                    th.col-2 Actions
                tbody
                  = f.fields_for :write_off_books do |f2|
                    = render partial: "write_offs/partials/add_book", locals: { book: f2.object&.book }


            = f.submit "Confirm", class: "btn btn-success float-right"

app/views/write_offs/show.html.slim
.container
  .row
    .col-12
      .float-left
        h2 Write Off
  hr
  .row
    .col-12
      = form_for @write_off do |f|    
        .row   
          .col-4
            .form-group
              strong User
              br/
              = @write_off.user.username

            .form-group
              strong Total Price
              br/
              = @write_off.total_price

            .form-group
              strong Write Off Date
              br/
              = l(@write_off.write_off_date.to_date, format: :default) rescue "-"            

            .form-group
              strong Remark
              br/
              = @write_off.remark
          
          .col-8          
            .col-12.mb-5
              table.table.table-sm.add-book-table
                thead
                  tr
                    th Books
                    th Price                    
                tbody
                  - @write_off.write_off_books.each do |write_off_book|
                    tr 
                      td = write_off_book&.book&.name
                      td = write_off_book&.price
                