config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :users do
    resources :admins
    resources :students do
      collection do
        post :import
      end
    end
    resources :teachers do
      collection do
        post :import
      end
    end
  end
  
  namespace :settings do
    resource :penalty_costs
    resource :backups
  end

  resources :borrowers do
    collection do 
      get :ajax_select2
    end
  end

  resources :books do
    collection do
      post :import
    end
  end
  
  resources :returns do
    collection do
      post :add_book
    end
  end
  
  resources :loans do 
    collection do
      post :add_book
    end
  end

  resources :write_offs do
    collection do
      post :add_book
    end
  end

  resources :late_returns

  namespace :reports do
    resources :loans do
      collection do
        get :top_rank
        get :by_year
        get :by_class
        get :detail
        post :detail
      end
    end
  end

  root "users/students#index"
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/users/admins_controller.rb
class Users::AdminsController < Users::BaseController
  before_action :set_user, only: %I[edit update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "This users has been created."
      redirect_to users_admins_path
    else
      flash[:error] = "Sorry unable to create user due to #{@user.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "This users has been updated."
      redirect_to users_admins_path
    else
      flash[:error] = "Sorry unable to update user due to #{@user.errors.full_messages.to_sentence}"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(%I[username email password password_confirmation])
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/users/students_controller.rb
class Users::StudentsController < Users::BaseController
  before_action :set_student, only: %I[edit update]

  def index
    respond_to do |format|
      format.html
      format.json { render json: StudentsDatatable.new(view_context) }
      format.xlsx { @students = Borrower.students }
    end
  end

  def new
    @student = Borrower.new
  end

  def edit; end

  def create
    @student = Borrower.new(borrower_params)
    if @student.save
      flash[:success] = "This students has been created."
      redirect_to users_students_path
    else
      flash[:error] = "Sorry unable to create student due to #{@student.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def update
    if @student.update(borrower_params)
      flash[:success] = "This students has been updated."
      redirect_to users_students_path
    else
      flash[:error] = "Sorry unable to update student due to #{@student.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def import
    @students = Borrower.import_students(params[:file])
    flash[:success] = "The students has been imported."
    redirect_to users_students_path
  end

  private

  def borrower_params
    params.require(:borrower).permit(%I[code name year school_class])
  end

  def set_student
    @student = Borrower.students.find(params[:id])
  end
end

app/controllers/users/teachers_controller.rb
class Users::TeachersController < Users::BaseController
  before_action :set_teacher, only: %I[edit update]

  def index
    respond_to do |format|
      format.html
      format.json { render json: TeachersDatatable.new(view_context) }
      format.xlsx { @teachers = Borrower.teachers }
    end
  end

  def new
    @teacher = Borrower.new
  end

  def edit; end

  def create
    @teacher = Borrower.new(borrower_params)
    @teacher.role = "teacher"
    if @teacher.save
      flash[:success] = "This teachers has been created."
      redirect_to users_teachers_path
    else
      flash[:error] = "Sorry unable to create teacher due to #{@teacher.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def update
    if @teacher.update(borrower_params)
      flash[:success] = "This teachers has been updated."
      redirect_to users_teachers_path
    else
      flash[:error] = "Sorry unable to update teacher due to #{@teacher.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def import
    @teachers = Borrower.import_teachers(params[:file])
    flash[:success] = "The teachers has been imported."
    redirect_to users_teachers_path
  end

  private

  def borrower_params
    params.require(:borrower).permit(%I[code name])
  end

  def set_teacher
    @teacher = Borrower.teachers.find(params[:id])
  end
end

app/views/users/students/_form.html.slim
  .form-group
    = f.label :code, "Code"
    = f.text_field :code, class: "form-control", placeholder: "Code", required: true

  .form-group
    = f.label :name, "Name"
    = f.text_field :name, class: "form-control", placeholder: "Name", required: true

  .form-group
    = f.label :year, "Year"
    = f.select :year, options_for_select((1..6).to_a,@student.year), { include_blank: "Please select a year" }, class: "form-control", required: true

  .form-group
    = f.label :school_class, "Class"
    = f.text_field :school_class, class: "form-control", placeholder: "EG: 3M, 3k (Only one)", required: true
  
  .form-action.row
    .col-12
      .float-left
        = f.submit "Submit", class: "btn btn-primary"
      .float-right
        = link_to "Back", users_teachers_path, class: "btn btn-secondary"

app/views/users/students/edit.html.slim
.container
  .row.mt-3.mb-3
    .col-12
      h3 Edit Student 
  hr   
    = form_for [:users, @student], url: users_student_path(@student), method: :patch do |f|   
      = render partial: "form", locals: { f: f }

app/views/users/students/index.html.slim
.container
  .row
    .col-12      
      center 
        .alert.alert-success
          p If this is the main server you may access your application through this IP: http://#{Socket.ip_address_list.detect(&:ipv4_private?).try(:ip_address)}:3000

    .col-12
      .float-left
        h2 Students
      .float-right
        .row
          .dropdown
            button#exportMenuButton.btn.btn-secondary.dropdown-toggle.mr-3.float-left aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button"
              | Export
            .dropdown-menu aria-labelledby="exportMenuButton" 
              = link_to "Students (xlsx)", users_students_path(format: :xlsx), target: "_blank", class: "dropdown-item"

          button.btn.btn-primary.float-left.mr-3 data-target="#importModal" data-toggle="modal" type="button" Import (.xlsx)
          = link_to "Add Student", new_users_student_path, class: "btn btn-success"
  hr

  table.table.ajax-datatable data-source="#{users_students_path(format: :json)}"
    thead
      tr
        th #
        th Code
        th Name
        th Year
        th Action

#importModal.modal.fade aria-hidden="true" aria-labelledby="importModal" role="dialog" tabindex="-1" 
  .modal-dialog role="document" 
    .modal-content
      .modal-header
        h5#exampleModalLabel.modal-title Import Students (.xlsx)
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
      = form_for "", url: import_users_students_path, method: :post do |f|
        .modal-body
          span * Take note code is the unique identity for students
          = f.file_field "file", required: true, accept: ".xlsx"
        .modal-footer
          = link_to "Download File", root_url+'xlsx/students.xlsx', class: "btn btn-danger mr-auto"        
            
          button.btn.btn-secondary data-dismiss="modal" type="button"  Close
          = f.submit "Import", class: "btn btn-success"

app/views/users/students/new.html.slim
.container
  .row.mt-3.mb-3
    .col-12
      h3 Create Student 
  hr
    = form_for [:users, @student], url: users_students_path, method: :post do |f|   
      = render partial: "form", locals: { f: f }