config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :users do
    resources :admins
    resources :students do
      collection do
        post :import
      end
    end
    resources :teachers do
      collection do
        post :import
      end
    end
  end
  
  namespace :settings do
    resource :penalty_costs
    resource :backups
  end

  resources :borrowers do
    collection do 
      get :ajax_select2
    end
  end

  resources :books do
    collection do
      post :import
    end
  end
  
  resources :returns do
    collection do
      post :add_book
    end
  end
  
  resources :loans do 
    collection do
      post :add_book
    end
  end

  resources :write_offs do
    collection do
      post :add_book
    end
  end

  resources :late_returns

  namespace :reports do
    resources :loans do
      collection do
        get :top_rank
        get :by_year
        get :by_class
        get :detail
        post :detail
      end
    end
  end

  root "users/students#index"
end

app/models/return.rb
class Return < ApplicationRecord
  belongs_to :borrower
  has_many :loan_books

  accepts_nested_attributes_for :loan_books, allow_destroy: true
end

app/controllers/returns_controller.rb
class ReturnsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_return, only: %I[show]

  def index
    respond_to do |format|
      format.html
      format.json { render json: ReturnsDatatable.new(view_context) }
    end
  end

  def new
    @return = Return.new
    @return.return_date = Time.zone.today
  end

  def show; end

  def create
    @return = Return.new(return_params)
    if @return.save
      set_return_books
      flash[:success] = "This return has been created."
      check_redirection      
    else
      flash[:error] = "Sorry unable to create book due to #{@return.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def add_book
    @book = Book.find_by(barcode: params[:barcode])
    @loan_book = LoanBook.find_by(book_id: @book&.id, status: "loan")
  end

  private

  def return_params
    params.require(:return).permit([:borrower_id, :return_date, :remark])
  end

  def set_return
    @return = Return.find(params[:id])
  end

  def set_return_books
    loan_book_ids = params["return"]["loan_books_attributes"].keys
    loan_books = LoanBook.where(id: loan_book_ids, status: "loan")
    loan_books.update_all(return_id: @return.id)
    loan_books.each{|x| x.return! if x.may_return? }
  end

  def check_redirection
    redirect_to return_path(@return)
  end
end

app/views/returns/add_book.js.erb
$(".barcode-input").val("")

<% if @book.present? %>
  <% if @loan_book.present? %>
    if ($("#book-id-<%= @book.id %>").size() == 0) {
      $(".add-book-table").find("tbody").append("<%= j render partial: 'returns/partials/add_book', locals: { book: @book, loan_book: @loan_book } %>")
    } else {
      alert("Book already added!")
    }
  <% else %>
    alert("No loan record for this book!")
  <% end %>  
<% else %>
  alert("Book not found! Please scan again.")
<% end %>

app/views/returns/index.html.slim
.container
  .row
    .col-12
      .float-left
        h2 Returns
      .float-right
        = link_to "Add Return", new_return_path, class: "btn btn-success"
  hr

  table.table.ajax-datatable data-source="#{returns_path(format: :json)}"
    thead
      tr
        th #
        th Borrower
        th Return Date
        th Action

app/views/returns/new.html.slim
.container
  .row
    .col-12
      .float-left
        h2 New Return
  hr
  .row
    .col-12
      = form_for "", url: add_book_returns_path, remote: true, method: :post do |f|        
        .d-flex.justify-content-center
          .form-group.col-8.mb-5
            = f.label :barcode, "Scann Barcode Here", class: "text-center"
            = text_field "", "barcode", class: "form-control barcode-input", placeholder: "Scann Barcode Here"
    .col-12
      = form_for @return do |f|    
        .row   
          .col-4
            .form-group
              = f.label :borrower_id, "Borrower"
              = f.select :borrower_id, options_for_select([], @return.borrower_id), {}, class: "form-control ajax-select2", data: { url: ajax_select2_borrowers_url(format: :json) }, required: true

            .form-group
              = f.label :return_date, "Loan Date"
              = f.text_field :return_date, class: "form-control", readonly: true, value: l(@return.return_date.to_date, format: :default)
            
            .form-group
              = f.label :remark, "Remark"
              = f.text_area :remark, class: "form-control", placeholder: "Remark"
        
          .col-8          
            .col-12.mb-5
              table.table.table-sm.add-book-table
                thead
                  tr
                    th Borrow Date
                    th Borrower
                    th Books
                    th Due Date
                    th Late Day
                    th Actions
                tbody
                  = f.fields_for :loan_books do |f2|
                    = render partial: "returns/partials/add_book", locals: { book: f2.object&.book, loan_book: f2.object }


            = f.submit "Confirm", class: "btn btn-success float-right"

app/views/returns/show.html.slim
.container
  .row
    .col-12
      .float-left
        h2 Return
  hr
  .row
    .col-12
      = form_for @return do |f|    
        .row   
          .col-4
            .form-group
              strong Borrower
              br/
              = @return.borrower.name

            .form-group
              strong Return Date
              br/
              = l(@return.return_date.to_date, format: :default) rescue "-"
            
            .form-group
              strong Remark
              br/
              = @return.remark
          
          .col-8          
            .col-12.mb-5
              table.table.table-sm.add-book-table
                thead
                  tr
                    th Books
                    th Loan Date
                    th Due Date
                    th Return Date
                    th Late Day
                tbody
                  - @return.loan_books.each do |loan_book|
                    tr 
                      td = loan_book&.book&.name                      
                      td = l(loan_book.loan_date.to_date, format: :default) rescue "-"
                      td = l(loan_book.due_date.to_date, format: :default) rescue "-"
                      td = l(loan_book.return_date.to_date, format: :default) rescue "-"
                      td = loan_book.display_late_day