config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :users do
    resources :admins
    resources :students do
      collection do
        post :import
      end
    end
    resources :teachers do
      collection do
        post :import
      end
    end
  end
  
  namespace :settings do
    resource :penalty_costs
    resource :backups
  end

  resources :borrowers do
    collection do 
      get :ajax_select2
    end
  end

  resources :books do
    collection do
      post :import
    end
  end
  
  resources :returns do
    collection do
      post :add_book
    end
  end
  
  resources :loans do 
    collection do
      post :add_book
    end
  end

  resources :write_offs do
    collection do
      post :add_book
    end
  end

  resources :late_returns

  namespace :reports do
    resources :loans do
      collection do
        get :top_rank
        get :by_year
        get :by_class
        get :detail
        post :detail
      end
    end
  end

  root "users/students#index"
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :borrower
  has_many :loan_books

  accepts_nested_attributes_for :loan_books, allow_destroy: true
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_loan, only: %I[show]

  def index
    respond_to do |format|
      format.html
      format.json { render json: LoansDatatable.new(view_context) }
    end
  end

  def new
    @loan = Loan.new
    @loan.loan_date = Time.zone.today
    @loan.day = PenaltyCost.first.days
    @loan.due_date = @loan.loan_date + @loan.day
  end

  def show; end

  def create
    @loan = Loan.new(loan_params)
    set_loan_books
    if @loan.save
      flash[:success] = "This loan has been created."
      redirect_to loan_path(@loan)
    else
      flash[:error] = "Sorry unable to create book due to #{@loan.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def add_book
    @book = Book.find_by(barcode: params[:barcode])
  end

  private

  def loan_params
    params.require(:loan).permit([:borrower_id, :loan_date, :day, :due_date, :remark, loan_books_attributes: [:id, :book_id]])
  end

  def set_loan
    @loan = Loan.find(params[:id])
  end

  def set_loan_books
    @loan.total_quantity = @loan.loan_books.size
    @loan.year = @loan.borrower&.year
    @loan.school_class = @loan.borrower&.school_class
    @loan.borrower_role = @loan.borrower&.role

    @loan.loan_books.each do |loan_book|
      loan_book.borrower_id = @loan.borrower_id
      loan_book.loan_date = @loan.loan_date
      loan_book.due_date = @loan.due_date
      loan_book.day = @loan.day
      loan_book.year = @loan.borrower&.year
      loan_book.school_class = @loan.borrower&.school_class
      loan_book.borrower_role = @loan.borrower&.role
    end
  end
end

app/controllers/reports/loans_controller.rb
class Reports::LoansController < ApplicationController
  before_action :authenticate_user!

  def top_rank
    if params[:commit].present?
      start_date = "1-1-#{params[:year]}".to_date
      end_date = "1-#{params[:month]}-#{params[:year]}".to_date.end_of_month
      date_ranges = (start_date..end_date)
      @loan_rank = Loan.where(loan_date: date_ranges).group(:borrower_id).sum(:total_quantity)
    end
  end

  def by_year
    if params[:commit].present?
      start_date = "1-#{params[:month]}-#{params[:year]}".to_date
      end_date = start_date.end_of_month
      date_ranges = (start_date..end_date)
      @result = Loan.select("loans.year, SUM(loans.total_quantity) AS quantity").where(loan_date: date_ranges).order("quantity desc").group(:year).limit(5)
    end
  end

  def by_class
    if params[:commit].present? or params[:format] == "xlsx"
      start_date = "1-#{params[:month]}-#{params[:year]}".to_date
      end_date = start_date.end_of_month
      date_ranges = (start_date..end_date)
      @result = Loan.select("borrower_id, SUM(loans.total_quantity) AS quantity")
                  .where(loan_date: date_ranges, school_class: params[:class])
                  .order("quantity desc")
                  .group(:borrower_id)
                  .group_by(&:borrower_id)
                  .to_h

      @borrowers = Borrower.where(id: @result.keys)

      loan_books = LoanBook.joins(:book, :loan)
                    .where(loans: { loan_date: date_ranges, school_class: params[:class]})

      @result_books = loan_books
                        .select("loan_books.borrower_id, books.language, count(*)")
                        .group("loan_books.id, loan_books.borrower_id, books.language")
                        .group_by{|x| [x&.borrower_id, x&.language]}

      @languages = loan_books.collect{|x| x&.book&.language.to_s }.uniq.sort
    end
  end

  def detail
    if params[:format] == "xlsx"
      start_date = "1-#{params[:month]}-#{params[:year]}".to_date
      end_date = start_date.end_of_month
      date_ranges = (start_date..end_date)
      @loan_books = LoanBook.joins(:borrower, :book).select(%Q{
                      loan_books.school_class,
                      borrowers.name AS borrower_name,
                      books.name AS book_name,
                      books.barcode AS barcode,
                      loan_books.loan_date,
                      loan_books.due_date,
                      loan_books.return_date
                    }).where(school_class: params[:school_class], loan_date: date_ranges)
                    .order(:loan_date)
    end
  end
end

app/views/loans/add_book.js.erb
$(".barcode-input").val("")

<% if @book.present? %>
  if ($("#book-id-<%= @book.id %>").size() == 0) {
    $(".add-book-table").find("tbody").append("<%= j render partial: 'loans/partials/add_book', locals: { book: @book } %>")
  } else {
    alert("Book already added!")
  }  
<% else %>
  alert("Book not found! Please scan again.")
<% end %>

app/views/loans/index.html.slim
.container
  .row
    .col-12
      .float-left
        h2 Loans
      .float-right
        = link_to "Add Loan", new_loan_path, class: "btn btn-success"
  hr

  table.table.ajax-datatable data-source="#{loans_path(format: :json)}"
    thead
      tr
        th #
        th Borrower
        th Loan Date
        th Due Date
        th Action

app/views/loans/new.html.slim
.container
  .row
    .col-12
      .float-left
        h2 New Loan
  hr
  .row
    .col-12
      = form_for "", url: add_book_loans_path, remote: true, method: :post do |f|        
        .d-flex.justify-content-center
          .form-group.col-8.mb-5
            = f.label :barcode, "Scann Barcode Here", class: "text-center"
            = text_field "", "barcode", class: "form-control barcode-input", placeholder: "Scann Barcode Here"
    .col-12
      = form_for @loan do |f|    
        .row   
          .col-4
            .form-group
              = f.label :borrower_id, "Borrower"
              = f.select :borrower_id, options_for_select([], @loan.borrower_id), {}, class: "form-control ajax-select2", data: { url: ajax_select2_borrowers_url(format: :json) }, required: true

            .form-group
              = f.label :loan_date, "Loan Date"
              = f.text_field :loan_date, class: "form-control", readonly: true, value: l(@loan.loan_date.to_date, format: :default)
            
            .form-group
              = f.label :day, "Day"
              = f.text_field :day, class: "form-control", readonly: true

            .form-group
              = f.label :due_date, "Due Date"
              = f.text_field :due_date, class: "form-control", readonly: true, value: l(@loan.due_date.to_date, format: :default)

            .form-group
              = f.label :remark, "Remark"
              = f.text_area :remark, class: "form-control", placeholder: "Remark"
          
          .col-8          
            .col-12.mb-5
              table.table.table-sm.add-book-table
                thead
                  tr
                    th.col-10 Books
                    th.col-2 Actions
                tbody
                  = f.fields_for :loan_books do |f2|
                    = render partial: "loans/partials/add_book", locals: { book: f2.object&.book }


            = f.submit "Confirm", class: "btn btn-success float-right"

app/views/loans/show.html.slim
.container
  .row
    .col-12
      .float-left
        h2 Loan
  hr
  .row
    .col-12
      = form_for @loan do |f|    
        .row   
          .col-4
            .form-group
              strong Borrower
              br/
              = @loan.borrower.name

            .form-group
              strong Loan Date
              br/
              = l(@loan.loan_date.to_date, format: :default) rescue "-"

            .form-group
              strong Days
              br/
              = @loan.day
            
            .form-group
              strong Due Date
              br/
              = l(@loan.due_date.to_date, format: :default) rescue "-"

            .form-group
              strong Remark
              br/
              = @loan.remark
          
          .col-8          
            .col-12.mb-5
              table.table.table-sm.add-book-table
                thead
                  tr
                    th Books
                    th Loan Date
                    th Due Date
                    th Remaining Days
                tbody
                  - @loan.loan_books.each do |loan_book|
                    tr 
                      td = loan_book&.book&.name
                      td = l(loan_book.loan_date.to_date, format: :default) rescue "-"
                      td = l(loan_book.due_date.to_date, format: :default) rescue "-"
                      td = (loan_book.due_date - Time.zone.today).to_i rescue "-"